### ISSUE TITLE
requestPolicyExchange does not re-request in production

### ISSUE THREAD

**Issue by Yama-Tomo** [urql-graphql/urql#3508] opened 2024-02-18 02:27 UTC
### Describe the bug

TTL-based re-request occurs in development mode but not in production.
I created a repository for reproduction. You can try each with `yarn dev` and `yarn prod`.

### Reproduction

https://github.com/Yama-Tomo/request-policy-exchange-bug

### Urql version

- urql@4.0.6
- @urql/core@4.2.3
- @urql/exchange-request-policy@1.0.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2024-02-18 05:20
This sounds like a duplicate of #3462.

So, I'm not convinced your core version is accurate here in your report. Does that sound about right? https://github.com/urql-graphql/urql/pull/3464

**Comment by Yama-Tomo** [comment] 2024-02-18 07:41
yes. The repository for reproduction uses version 4.2.3

**Comment by Yama-Tomo** [comment] 2024-02-20 08:17
Looks like you are right, it was fixed in #3464. 
However, the code published in npm doesn't seem to have it added :thinking: (I patched it to 4.2.3 and it works.)

This may have affected.
https://github.com/urql-graphql/urql/blob/87c4bd95631d83e4f33e23fcf066b73aeae5a768/scripts/babel/transform-debug-target.mjs#L47-L52

**Closed** 2024-03-06 10:18 UTC
