### ISSUE TITLE
Subscription does not trigger request when used with composables across multiple components with vue router

### ISSUE THREAD

**Issue by Ancient-Dragon** [urql-graphql/urql#3010] opened 2023-03-06 21:42 UTC
### Describe the bug

This is a weird one, essentially we have some loading screen which does some pre-requisites to load our application. Then we switch over to main "Wrapper" vue file which initiates a subscription, this works fine if you do not go to the pre-requisite first, however upon going to the pre-requisite I've found that the subscription is not triggered, I can see it changing isPaused to true, and I can try and toggle isPaused but to no-avail, essentially the subscription will never be triggered.

To reproduce using my example run the vite application using dev (if you need to use a server let me know and I can try and get my backend working although I was able to reproduce without the backend running by looking at my logs.

1. Run vite
2. go to the application and go to /test
3. watch the logs to see what happens, you should get the following log messages:
```
Changing route Home.vue:13:10
Debugging Subscription: resume
```

But you will not see this log messages:

```
Debugging Subscription: Subscribe
```

and no network request will be made.

_Note_ if you want to see the logs I'm expecting just refresh the page when you're on the /query url

### Reproduction

https://github.com/Ancient-Dragon/dgs-sse-subscriptions-post-example

### Urql version

"@urql/vue": "^1.0.4",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2023-03-06 23:55
I don't think I'm currently able to run your reproduction, so essentially, there's not much value I can gain from that just yet except for reading this 😅 Sorry! That said, I only tried to run it very briefly and assume that the API doesn't run locally, and this isn't quite a minimal reproduction just yet?

Anyways, I find this line a little suspicious:
https://github.com/Ancient-Dragon/dgs-sse-subscriptions-post-example/blob/6a97a66f2cac499d30c914bc9ef2226f82d111bf/src/composables/UseStocks.ts#L14

Essentially, the reason why that makes me suspicious is that this code assumes it can call `useQuery` once and then reuse the resulting object. However, this resulting object is actually tied to the component it was rendered in. That's why it also should only be called inside `setup()`.

That's because it needs to know when the subscription to the query stops. So, not to assume any knowledge here; a single GraphQL query can still be updated and the "stream" of results that the `Client` gives to the bindings (like Vue's `useQuery` bindings) hence can receive updates over time (which obviously you're making use of with SSE): https://formidable.com/open-source/urql/docs/architecture/

So, we're tying the _unsubscription_ (and that's the same for e.g. the React and Preact bindings) to the unmount of the component.
It's basically saying: Give me the query results for _this_ query (input variables, which can reactively change), but stop giving me the results when I give you new inputs, or when I unmount.

Usually, `@vue/reactivity` does this automatically for us even. We actually have a `useClientHandle` wrapper that makes this clearer: https://github.com/urql-graphql/urql/blob/1aa3cb5c65bbef376776bba4e2fa05630031956d/packages/vue-urql/src/useClientHandle.ts#L44-L47

So, in other words, obviously, it appears though you'll get new results using `useStocks`, but as soon as the component that first mounted it unmounts, the reactivity model in Vue will stop all effects, which stops the "Query source" on `@urql/core`'s `Client`.

**However,** that's also partly the solution. `urql`'s `Client` is actually smarter than it may appear and will make sure that it keeps a handle on which queries are active. As long as you have at least one component "actively subscribed" to a given query+variables combo (operation), it'll keep this operation active.
Furthermore, with the `dedupExchange`, you'll also never run the risk of having the same query active twice.

So, I'd recommend you to have a quick look [at this memoisation](https://github.com/Ancient-Dragon/dgs-sse-subscriptions-post-example/blob/6a97a66f2cac499d30c914bc9ef2226f82d111bf/src/composables/UseStocks.ts#L14), and try removing it.

If you need to manually manage a subscription (i.e. you may have no components subscribed to something you need to stay active for a while) it may be worth looking into manually starting the subscription without the bindings: https://formidable.com/open-source/urql/docs/advanced/subscriptions/#one-off-subscriptions

**Comment by Ancient-Dragon** [comment] 2023-03-07 08:27
Hey @kitten thanks for the response, do you happen to have the error you got when running the example app? You can try running the server script if it's not loading although that wasn't used for the subscription (you shouldn't need the api to work for this as it's captured by logs).

So that line was put in to prevent [this issue](https://github.com/urql-graphql/urql/issues/2990), as we had multiple components calling the same subscription & calling resume / pause. Leading to multiple subscriptions being opened. I couldn't find any documentation on how the dedup exchange works on whether you need to provide a specific field for it work. Would you be able to point me in the right direction? 

I'll also look into the one off subscriptions as well but ideally I think we'd like to use the useSubscription composable.

**Comment by kitten** [comment] 2023-03-07 14:11
To be fair, no matter where we go from here or whether I run the example, I'm pretty convinced that the issue is this shared object 😅 So, in other words, just because that's how you're trying to share the subscription, that doesn't mean it'll actually work.

However, I think I found the issue related to why subscriptions aren't being deduplicated and why you're seeing duplicate subscriptions being started: https://github.com/urql-graphql/urql/pull/3015

**Comment by kitten** [comment] 2023-03-07 15:37
@Ancient-Dragon: We have a prerelease ready by CI. You should be able to install `@urql/core` with version `0.0.0-canary-20230307152911` (the `canary` release — you can also install `@urql/core@canary` for the tag), and this should include the fix from #3015.
Hopefully, if you then remove the variable, the `dedupExchange` should deduplicate the subscription successfully (it's already included in `defaultExchanges`) and since the local variable is removed, this should work as expected.

**Comment by Ancient-Dragon** [comment] 2023-03-07 15:51
Hi @kitten  you mentioned about removing the variable? This isn't an option for us we need the variable, would you be able to explain why the variable would cause the dedup exchange to break?

**Comment by kitten** [comment] 2023-03-07 16:56
Reusing the return value of `useQuery` is what I'm referring to. This doesn't break the `dedup` exchange, it breaks Vue's reactivity model, as per the comment prior: https://github.com/urql-graphql/urql/issues/3010#issuecomment-1457233843

**Comment by Ancient-Dragon** [comment] 2023-03-07 17:30
Apologies, I thought you meant the graphql variable! 

However I did try this out with my above example and still I was unable to resume / pause the subscription /query url.

**Comment by kitten** [comment] 2023-03-07 22:00
It works correctly, I got your example to run.
You can't just share these reactive values using a function across several files and expect them to all be reactive across multiple components. You can instantiate a query in one place and then pass these values on as props, or otherwise, but that's about it. The same goes for the pause state.

Basically, because you have these nested routes, when you have your subscription in multiple places, and you only pause them in one place, then they'll still be active somewhere else. That's why you're not seeing an unsubscribe & subscribe. The `Client` in `@urql/core` sees that your subscription was still active.

So, I'll have to close this as a usage issue 😅 Sorry! But an issue isn't the right place any longer to look at this. I believe the original issue of duplicate subscriptions will be resolved though, although, I didn't see any evidence of duplicate subscriptions in your reproduction, even while making the necessary changes to make this work

**Closed by kitten** 2023-03-07 22:00 UTC
