### ISSUE TITLE
@urql/exchange-persisted Module name, 'crypto' does not resolve to a valid URL.

### ISSUE THREAD

**Issue by badtant** [urql-graphql/urql#3523] opened 2024-03-06 09:21 UTC
### Describe the bug

Hi,
I'm getting some errors logged from @urql/exchange-persisted.

Module name, 'crypto' does not resolve to a valid URL.
Pointing to this line: p = new Function('return import("crypto")')();

The issue seems to be mainly in safari

### Reproduction

-

### Urql version

"urql": "4.0.6",
"@urql/exchange-persisted": "4.1.1",

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2024-03-06 09:34
Do you have a reproduction?

This shouldn't ever happen since we only attempt to import the Node Crypto module if the WebCrypto API is unavailable. If that was unavailable then that browser is well outside of our range of supported browsers

- The relevant code: https://github.com/urql-graphql/urql/blob/d2c7441731bfc636a57c8864ea49464d59c13d6f/exchanges/persisted/src/sha256.ts#L26
- Browser Support table for WebCrypto `subtle`: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle

**Comment by badtant** [comment] 2024-03-06 09:51
I haven't been able to reproduce it myself but here are som data from sentry
![sentry](https://github.com/urql-graphql/urql/assets/400265/175c6217-10c8-4797-ab93-e3589e3309fe)

**Comment by kitten** [comment] 2024-03-06 09:56
To be honest, I kind of expected this to be an issue report from an error analytics tool, like Sentry 😅 

That's because this honestly doesn't sound like it would ever happen on "real" devices, but instead on requests that fake a user agent but are potentially crawlers.

That said, given that there's a lot of different devices in your report and hence a lot of user agents, there's still a chance there's something odd going on. Mind you though we haven't seen a similar report for a while so this is definitely weird, and could also hint at a faulty polyfill (?)

I'm afraid we won't have much to go on without a reproduction, but I realise that this might be tricky ❤️

**Comment by badtant** [comment] 2024-03-06 10:07
Yeah, I get it's really hard to do something without being able to reproduce it.
i'll keep testing different browsers/devices to see if I can get the error.

**Comment by badtant** [comment] 2024-03-14 07:41
Ahh, thanks for pointing that out!
When i check now the reports are not on https. I have no idea how they end up on http though... they should be redirected to https :)

**Comment by kitten** [comment] 2024-03-14 17:11
Then, if you don't mind, I'll close this as unplanned for now, until we have some information of whether this comes down to a real browser with an available reproduction ✌️ happy to reopen this though when we've got something actionable, so no need to worry ❤️

**Closed by kitten** 2024-03-14 17:11 UTC
Labels: needs more info ✋
