### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'reduceRight')  

### ISSUE THREAD

**Issue by fan-droide** [urql-graphql/urql#3152] opened 2023-04-17 22:14 UTC
### Describe the bug

Following the documentation from Platformatic (https://oss.platformatic.dev/docs/getting-started/movie-quotes-app-tutorial/). After installing latest version (4.0.4) from @urql/core

npm install @urql/core graphql

The following snippet

```
import { createClient } from '@urql/core';

const graphqlClient = createClient({
  url: import.meta.env.PUBLIC_GRAPHQL_API_ENDPOINT,
  requestPolicy: "network-only"
});
```

it throws an error, saying:

**_Uncaught TypeError: Cannot read properties of undefined (reading 'reduceRight')_**

this points to the file compose.ts
 

### Reproduction

https://oss.platformatic.dev/docs/getting-started/movie-quotes-app-tutorial/#integrate-the-urql-graphql-client

### Urql version

"@urql/core": "^4.0.4"

It does not happen with 3.0.3

https://github.com/platformatic/tutorial-movie-quotes-app/blob/main/apps/movie-quotes-frontend/package.json

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/urql-graphql/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/urql-graphql/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment] 2023-04-17 23:32
Duplicate of #3144
Duplicate of #3145

**Closed by kitten** 2023-04-17 23:32 UTC
