### ISSUE TITLE
RFC: Custom `reexecuteOperation` function for document caching exchange

### ISSUE THREAD

**Issue by yukukotani** [urql-graphql/urql#3149] opened 2023-04-13 15:57 UTC
## Summary

Make it possible to custom `reexecuteOperation` function that  executed when `cacheExchange` invalidates caches.

The background for this proposal is App Router introduced in Next.js 13. I'm running a query in Server Component so need to call [`router.refresh()`](https://beta.nextjs.org/docs/data-fetching/mutating) to invalidates (refetches) caches. 

## Proposed Solution

Since `cacheExchange` is just an Exchange object but not a function, we cannot pass `reexecuteOperation` as an option.

Thenfore I propose to create new function called `createCacheExchange`. The signature will be like below.

```ts
type CreateCacheExchangeOption = {
  reexecuteOperation?: (client: Client, operation: Operation) => void,
}

export function createCacheExchange(options?: CreateCacheExchangeOption): Exchange { ... }

// keep current `cacheExchange`.
export const cacheExchange = createCacheExchange();
```

**Comment by yukukotani** [comment] 2023-04-16 08:48
@kitten Thanks for your feedback!

> First, the cache isn't actually really being used on the client-side, so I don't see why it should carry the responsibility of "destroying" the page/state when it does this, especially since this is basically a full reload on every mutation anyway.

Actually `router.refresh()` won't destroy the page/state. The states outside the query, such as form inputs, are preserved while refetching the query result from the server.

> As per that, you can use the mapExchange and reload the page if operation.context.requestPolicy === 'network-only' then, which is functionally equivalent.

In this case, `client.reexecuteOperation` which is called by default will do nothing. This is because the query is called in the server thenfore no one subscribes the operation result in the client.

So we can't use `mapExchange` to catch the cache refreshing.

**Comment by kitten** [comment] 2023-04-18 12:53
> client.reexecuteOperation which is called by default will do nothing. This is because the query is called in the server thenfore no one subscribes the operation result in the client.

I mean, that's by design. Either you rehydrate your GraphQL data on the client and let the client handle the GraphQL calls, or you handle them on the server-side 😅 So, full disclosure, we don't really see the point of handling this with server components and hence we haven't really looked into server components + urql just yet.

But the gist of it is, if you've got your `Client` in a server component, and the client-side has a `Client` that has no knowledge of the data, then how are we supposed to expect this to efficiently refetch? In general, you can always use the `Client` as a "dumb" GraphQL request without a `cacheExchange` and just call `router.refresh` manually after a mutation, since that's equivalent.

But if you're trying to use server components together with the document cache (or any other cache) I'm not really sure what value that'd bring, if the client never actually handles the GraphQL query responses.

**Comment by yukukotani** [comment] 2023-04-24 15:53
@kitten 

> we don't really see the point of handling this with server components

We don't need to handle "fetching" state on the client anymore if we run query on the server. There are others but this is one of the biggest benefits.

> I'm not really sure what value that'd bring, if the client never actually handles the GraphQL query responses.

I hope, in short, to use urql's Document Cache algorithm to determine whether to run `router.refresh`.

Let's consider that we initially run a query of whole page on the server then run some mutations on the client. Some mutations will update the query result and the others won't. The former need `router.refresh` and the latter don't. I'd like to determine it using the Document Cache algorithm.

Also I think it's better if we could run 2nd time query on the client instead of `router.refresh`, but in my understanding, we can't do this intuitively with current API because the first query is not fired by `useQuery` hook.

**Comment by kitten** [comment] 2023-05-07 12:14
Closing in favour of the response and discussion in #3208

**Closed** 2023-05-07 12:14 UTC
Labels: future 🔮
