### ISSUE TITLE
Can't get @stream directive working properly

### ISSUE THREAD

**Issue by robertherber** [urql-graphql/urql#2901] opened 2022-12-21 11:09 UTC
### Discussed in https://github.com/urql-graphql/urql/discussions/2888

<div type='discussions-op-text'>

<sup>Originally posted by **robertherber** December 15, 2022</sup>
```TypeScript
const client = createClient({ 
  url,
  fetchOptions: {
    headers: {
      accept: 'application/graphql-response+json, application/json, multipart/mixed' // <- without specifying this explicitly the request fails
    }
  } 
});

const query = `query {
  shops @stream {
    name
  }
}`

client.query(query)(dataStreamResult => {
  console.log('dataStreamResult', dataStreamResult)
})
```

Initially the request failed altogether, but I managed to get it to work on a "browser level" by specifying the accept headers explicitly. The request looks alright and identical (in the network inspector) to the successful attempt in GraphiQL. The `dataStreamResult` callback is getting called twice - but with an empty array in both cases.

I've gotta be missing something here - any help pointing me in the right direction would be greatly appreciated :)

Side note: It would be great with some documentation on `@stream` (and `@defer` as well)</div>

**Comment by JoviDeCroock** [comment] 2022-12-21 18:24
I have quickly tried in our [own example](https://github.com/urql-graphql/urql/tree/main/examples/with-defer-stream-directives) which just worked, we might need a reproduction here or more information about what's actually happening 😅 it's really hard for us to tell what exactly is going wrong here

**Comment by robertherber** [comment] 2022-12-22 01:36
@JoviDeCroock I can confirm your example works for me as well, thanks! 👍 Side note: it would be nice with a lockfile in the example, I had to change `@stream(initial_count: 3)` to `@stream(initialCount: 3)` to get it running when doing a fresh install.

Will look into making a repro of what doesn't work for me 👍

**Comment by kitten** [comment] 2023-01-10 16:22
@Abiti-936 That seems a little unrelated. As stated above, given the multipart transport, which is tested and implemented against "meros", and the `@stream` response (or `@defer`) the response should be stitched together properly.

So, if yoou can't isolate this against Qwik (which could also be the case since during SSR there's a choice to be made whether to wait for a fully stitched response or not), I'd be careful to conflate this issue with one with Qwik, which as of now has no official `urql` bindings, so isn't something I can weigh in on.

@robertherber: Given that it's hard too align on something here, I'm inclined to close this for now, and instead reopen this, if it's needed.

On a side-note, our `Accept` header is currently this:
https://github.com/urql-graphql/urql/blob/121b53b97dfdd5bb17a769d9b539de73322614dd/packages/core/src/internal/fetchOptions.ts#L60

This has recently changed and we'll have to adapt, but for context, the GraphQL over HTTP spec hasn't been finalised and passed yet, so it's a moving target: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#media-types

Now, depending on which server framework/implementation you use for multipart GraphQL incremental responses, you may have to change the `Accept` header. That's because that specific RFC part of the spec doesn't assume any different `Accept` header: https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md
How we interpreted that, and what I assume is sane, is that if the `Accept` header includes the GraphQL-over-HTTP media response type, it's assumed that a response can use this multipart protocol.

**Closed by kitten** 2023-01-10 16:22 UTC
Labels: needs more info ✋
